site_name: Nova Script Service Documentations
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Darkmode
      primary: darkblue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Lightmode
      primary: darkblue
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/DSnNQBn7us

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html

copyright:
  2024 <a href="https://www.youtube.com" target="_blank" rel="noopener">SuchterKing</a>